// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/lamxy/fiberhouse/example_application/module/example-module/model"
	"github.com/lamxy/fiberhouse/example_application/module/example-module/repository"
	"github.com/lamxy/fiberhouse/example_application/module/example-module/service"
	"github.com/lamxy/fiberhouse/frame"
)

// Injectors from api_provider.go:

func InjectExampleApi(ctx frame.ContextFramer) (*ExampleHandler, error) {
	exampleModel := model.NewExampleModel(ctx)
	exampleRepository := repository.NewExampleRepository(ctx, exampleModel)
	exampleService := service.NewExampleService(ctx, exampleRepository)
	exampleHandler := NewExampleHandler(ctx, exampleService)
	return exampleHandler, nil
}

func InjectHealthApi(ctx frame.ContextFramer) (*HealthHandler, error) {
	healthRepository := repository.NewHealthRepository(ctx)
	healthService := service.NewHealthService(ctx, healthRepository)
	healthHandler := NewHealthHandler(ctx, healthService)
	return healthHandler, nil
}
